deleteTraefikDeamon:
	kubectl delete clusterrolebinding.rbac.authorization.k8s.io/traefik-ingress-controller

deleteserviceaccount:
	kubectl delete serviceaccount/traefik-ingress-controller2

deletedeploymenteaccount:
	kubectl delete deployment.apps/traefik-ingress-controller


deleteTraefikDeployment:
	kubectl delete deployment.apps/traefik-ingress-controller
