apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  - port: 8889
    targetPort: 8889
    protocol: TCP
    name: http2
  selector:
    app: userservice
