{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ebl-chart.serviceAccountName" . }}
  labels:
{{ include "ebl-chart.labels" . | indent 4 }}
{{- end -}}
